### ISSUE TITLE
Incorrect Link in Excel Document

### ISSUE THREAD

**Issue by sbhuttan** [microsoft/DataMigrationTeam#22]
A link in "Worksheet in workload assessment tool" is pointing to incorrect link on McDonald's site. 

Worksheet available here - 
https://github.com/Microsoft/DataMigrationTeam/tree/master/Data%20Workload%20Assessment%20Model%20and%20Tool/Workload%20Assessment%20Tools

Here is the link to Information Asset Classification link - that redirects to MCD web site requiring employee login - 
https://dmc.accessmcd.com/content/mcmac/storagearea/wa1/b296d62eeb3a8efd2d2dc0760d533fd3/2553976.AssetPar.Single.File.0.tmp.x.pdf

**Comment by Kuldeep-Chauhan** [comment]
Thanks for highlighting the issue, this is resolved.
